package android.support.constraint;

public final class g {
    public final class a {
        public static final int barrier = 0x7F0B001C;
        public static final int bottom = 0x7F0B000E;
        public static final int chains = 0x7F0B001D;
        public static final int dimensions = 0x7F0B001E;
        public static final int direct = 0x7F0B001F;
        public static final int end = 0x7F0B000F;
        public static final int gone = 0x7F0B0014;
        public static final int invisible = 0x7F0B0015;
        public static final int left = 0x7F0B0010;
        public static final int none = 0x7F0B0020;
        public static final int packed = 0x7F0B001A;
        public static final int parent = 0x7F0B0016;
        public static final int percent = 0x7F0B0017;
        public static final int right = 0x7F0B0011;
        public static final int spread = 0x7F0B0018;
        public static final int spread_inside = 0x7F0B001B;
        public static final int standard = 0x7F0B0021;
        public static final int start = 0x7F0B0012;
        public static final int top = 0x7F0B0013;
        public static final int wrap = 0x7F0B0019;

        public a() {
            super();
        }
    }

    public final class b {
        public static final int[] ConstraintLayout_Layout = null;
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
        public static final int ConstraintLayout_Layout_barrierDirection = 6;
        public static final int ConstraintLayout_Layout_chainUseRtl = 7;
        public static final int ConstraintLayout_Layout_constraintSet = 8;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids = 9;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight = 10;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth = 11;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintCircle = 17;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 0x1F;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 0x20;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 0x2F;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 0x30;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 56;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 57;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 58;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 59;
        public static final int[] ConstraintLayout_placeholder = null;
        public static final int ConstraintLayout_placeholder_content = 0;
        public static final int ConstraintLayout_placeholder_emptyVisibility = 1;
        public static final int[] ConstraintSet = null;
        public static final int ConstraintSet_android_alpha = 9;
        public static final int ConstraintSet_android_elevation = 22;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 20;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 19;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotation = 16;
        public static final int ConstraintSet_android_rotationX = 17;
        public static final int ConstraintSet_android_rotationY = 18;
        public static final int ConstraintSet_android_scaleX = 14;
        public static final int ConstraintSet_android_scaleY = 15;
        public static final int ConstraintSet_android_transformPivotX = 10;
        public static final int ConstraintSet_android_transformPivotY = 11;
        public static final int ConstraintSet_android_translationX = 12;
        public static final int ConstraintSet_android_translationY = 13;
        public static final int ConstraintSet_android_translationZ = 21;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_layout_constrainedHeight = 23;
        public static final int ConstraintSet_layout_constrainedWidth = 24;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 25;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
        public static final int ConstraintSet_layout_constraintBottom_creator = 27;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 29;
        public static final int ConstraintSet_layout_constraintCircle = 30;
        public static final int ConstraintSet_layout_constraintCircleAngle = 0x1F;
        public static final int ConstraintSet_layout_constraintCircleRadius = 0x20;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 33;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 34;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 35;
        public static final int ConstraintSet_layout_constraintGuide_begin = 36;
        public static final int ConstraintSet_layout_constraintGuide_end = 37;
        public static final int ConstraintSet_layout_constraintGuide_percent = 38;
        public static final int ConstraintSet_layout_constraintHeight_default = 39;
        public static final int ConstraintSet_layout_constraintHeight_max = 40;
        public static final int ConstraintSet_layout_constraintHeight_min = 41;
        public static final int ConstraintSet_layout_constraintHeight_percent = 42;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 43;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 45;
        public static final int ConstraintSet_layout_constraintLeft_creator = 46;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 0x2F;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 0x30;
        public static final int ConstraintSet_layout_constraintRight_creator = 49;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 50;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 51;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 52;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 53;
        public static final int ConstraintSet_layout_constraintTop_creator = 54;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 55;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 56;
        public static final int ConstraintSet_layout_constraintVertical_bias = 57;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 58;
        public static final int ConstraintSet_layout_constraintVertical_weight = 59;
        public static final int ConstraintSet_layout_constraintWidth_default = 60;
        public static final int ConstraintSet_layout_constraintWidth_max = 61;
        public static final int ConstraintSet_layout_constraintWidth_min = 62;
        public static final int ConstraintSet_layout_constraintWidth_percent = 0x3F;
        public static final int ConstraintSet_layout_editor_absoluteX = 0x40;
        public static final int ConstraintSet_layout_editor_absoluteY = 65;
        public static final int ConstraintSet_layout_goneMarginBottom = 66;
        public static final int ConstraintSet_layout_goneMarginEnd = 67;
        public static final int ConstraintSet_layout_goneMarginLeft = 68;
        public static final int ConstraintSet_layout_goneMarginRight = 69;
        public static final int ConstraintSet_layout_goneMarginStart = 70;
        public static final int ConstraintSet_layout_goneMarginTop = 71;
        public static final int[] LinearConstraintLayout;
        public static final int LinearConstraintLayout_android_orientation;

        static {
            b.ConstraintLayout_Layout = new int[]{0x10100C4, 0x101011F, 0x1010120, 0x101013F, 0x1010140, 0x7F010000, 0x7F010001, 0x7F010002, 0x7F010003, 0x7F010004, 0x7F01000A, 0x7F01000B, 0x7F01000C, 0x7F01000D, 0x7F01000E, 0x7F01000F, 0x7F010010, 0x7F010011, 0x7F010012, 0x7F010013, 0x7F010014, 0x7F010015, 0x7F010016, 0x7F010017, 0x7F010018, 0x7F010019, 0x7F01001A, 0x7F01001B, 0x7F01001C, 0x7F01001D, 0x7F01001E, 0x7F01001F, 0x7F010020, 0x7F010021, 0x7F010022, 0x7F010023, 0x7F010024, 0x7F010025, 0x7F010026, 0x7F010027, 0x7F010028, 0x7F010029, 0x7F01002A, 0x7F01002B, 0x7F01002C, 0x7F01002D, 0x7F01002E, 0x7F01002F, 0x7F010030, 0x7F010031, 0x7F010032, 0x7F010033, 0x7F010034, 0x7F010035, 0x7F010036, 0x7F010037, 0x7F010038, 0x7F010039, 0x7F01003A, 0x7F01003B};
            b.ConstraintLayout_placeholder = new int[]{0x7F010005, 0x7F010007};
            b.ConstraintSet = new int[]{0x10100C4, 0x10100D0, 0x10100DC, 0x10100F4, 0x10100F5, 0x10100F7, 0x10100F8, 0x10100F9, 0x10100FA, 0x101031F, 0x1010320, 0x1010321, 0x1010322, 0x1010323, 0x1010324, 0x1010325, 0x1010326, 0x1010327, 0x1010328, 0x10103B5, 0x10103B6, 0x10103FA, 0x1010440, 0x7F01000A, 0x7F01000B, 0x7F01000C, 0x7F01000D, 0x7F01000E, 0x7F01000F, 0x7F010010, 0x7F010011, 0x7F010012, 0x7F010013, 0x7F010014, 0x7F010015, 0x7F010016, 0x7F010017, 0x7F010018, 0x7F010019, 0x7F01001A, 0x7F01001B, 0x7F01001C, 0x7F01001D, 0x7F01001E, 0x7F01001F, 0x7F010020, 0x7F010021, 0x7F010022, 0x7F010023, 0x7F010024, 0x7F010025, 0x7F010026, 0x7F010027, 0x7F010028, 0x7F010029, 0x7F01002A, 0x7F01002B, 0x7F01002C, 0x7F01002D, 0x7F01002E, 0x7F01002F, 0x7F010030, 0x7F010031, 0x7F010032, 0x7F010033, 0x7F010034, 0x7F010035, 0x7F010036, 0x7F010037, 0x7F010038, 0x7F010039, 0x7F01003A};
            b.LinearConstraintLayout = new int[]{0x10100C4};
        }
    }

}

